### ISSUE TITLE
Expose data as a property

### ISSUE THREAD

**Issue by ksobon** [ksobon/Mandrill#23]
Expose data as JSON string so that it can potentially be used elsewhere.

**Comment by ksobon** [comment]
This should do the trick: 

![image](https://cloud.githubusercontent.com/assets/529781/21085063/e1eb99b6-bfda-11e6-847e-4681ed20a1f9.png)

cc: @thazell

**Comment by thazell** [comment]
@ksobon Awesome!  That's even better.  Thanks
