### ISSUE TITLE
Dynamo has crashed

### ISSUE THREAD

**Issue by kevalsolanki10** [ksobon/Mandrill#64]
Dynamo core - 2.1.0.7500
Dynamo Revit - 2.1.0.7733

(Which version of Dynamo are you using? Go to Help > About if you're not sure.)

Revit version - 2019
(Which version of Revit are you using?)

Operating system
Windows 10

What did you do?
Tried to launch the report using the Mandrill. It contain the script of the bar chart.

What did you expect to see?
Bar chart showing the Room name & Area

What did you see instead?
Dynamo Crashed
![Crashed](https://user-images.githubusercontent.com/68247813/87345207-62ec9380-c56d-11ea-8028-bccca005dd12.JPG)

**Comment by kevalsolanki10** [comment]
Issue solved

**Comment by ksobon** [comment]
@kevalsolanki10 if you can post some more information, like a log file that was generated during this crash that would be great. Until then, I will close this issue. I just released a new version that took care of some of the eowp.exe related crashes. Please reopen this issue if it's still persisting.
