### ISSUE TITLE
ScatterPlotData list input

### ISSUE THREAD

**Issue by Vins-a-r** [ksobon/Mandrill#66]
Hi,
I'm using Mandrill for Grasshopper and, apparently, the ScatterPlotData does not work with a list input. In fact, when I try to plot a set of data, I only get the first point.
I downloaded the last updated version of the plug-in but it did not work for me.

Any suggestion about how to solve this issue?

Thank you!

Kind regards.

![Capture1](https://user-images.githubusercontent.com/40264179/136578709-af5f14c2-0eb0-48a4-8d3d-d5682b7fe45f.PNG)

**Comment by ksobon** [comment]
@Vins-a-r you have to pay attention to "Size" input. If you are providing a list of points, then you have to have a matching list of sizes. Here's an example: 

![image](https://user-images.githubusercontent.com/529781/136586018-2baf1776-de80-4129-bf72-937cba592151.png)

Also, there is a git book that explains data structures for most of these charts. It's for Dynamo, but very similar in Grasshopper. https://konradsobon.gitbooks.io/mandrill-primer/content/
