### ISSUE TITLE
Script error: Select.Html.dep

### ISSUE THREAD

**Issue by josols** [ksobon/Mandrill#7]
I recieve the following error when trying to create a pdf from a report:
![image](https://cloud.githubusercontent.com/assets/7080648/18776774/da8a72c6-816b-11e6-83ee-14603ade04c3.png)

here is a picture of the entire test workflow:
![pic1](https://cloud.githubusercontent.com/assets/7080648/18776860/5f99fe3c-816c-11e6-9954-1841b1563ac1.png)

**Comment by ksobon** [comment]
it should be fixed with latest release. 

![image](https://cloud.githubusercontent.com/assets/529781/18891816/ee1641e6-84d4-11e6-9158-80dc19e5ff9e.png)
